org.cryptomator.api.update.download.new=Download...
org.cryptomator.api.update.download.indeterminateProgress=Downloading...
org.cryptomator.api.update.download.progress=Downloading... %1.0f%%
org.cryptomator.api.update.download.done=Downloaded.

org.cryptomator.api.update.updateStep.EXIT=Exiting...
org.cryptomator.api.update.updateStep.RETRY=Retry